### PR TITLE
Added clean command to rust build.

### PR DESCRIPTION
**Pull request by maltesander**

### CODE REVIEW

**Review by lfrancke — CHANGES_REQUESTED** [review]
Sorry, the dependabot changes interferred, could you update again?

**Comment by lfrancke** [comment]
I'm only on the phone but it still looks wrong I believe

**Comment by maltesander** [comment]
Im not sure what looks wrong? The conflicts were resolved yesterday?

**Comment by lfrancke** [comment]
To me it looks like you remove the version numbers again from the GitHub actions.

I'm only on the phone so maybe it's a display error.

**Comment by maltesander** [comment]
No you were right, i clicked on update branch to avoid conflicts and it got removed.

**Review by lfrancke — APPROVED** [review]

**Pull request merged**
